### ISSUE TITLE
Unable to setup Linux mint 17.2

### ISSUE THREAD

**Issue by progsmile** [lsmithso/skcmd#1]
When run this commant `sudo python setup.py install`
have such error:
`Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from ez_setup import use_setuptools
ImportError: No module named ez_setup`

please, help)

**Comment by lsmithso** [comment]
Hi: Try -

 sudo apt-get install python-setuptools

You might also have to do:

sudo easy_install  skype4py

skcmd.py does still work, but needs some TLC. Maybe over the Xmas
break I'll sort the packaging out.

progsmile writes:

> When run this commant `sudo python setup.py install`
> have such error:
> Traceback (most recent call last):
>   File "setup.py", line 4, in <module>
>     from ez_setup import use_setuptools
> ImportError: No module named ez_setup
> 
> please, help)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lsmithso/skcmd/issues/1

## 

Les Smithson
